# Generated by Django 4.0.4 on 2022-10-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0007_alter_product_id_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
